services:
  - type: web
    name: eplano-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
